name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag get-cpu-info:latest
        
      - name: Run the Docker image
        run: docker run -d get-cpu-info:latest
        
      - name: Get container ID
        run: containerID=$(docker container ls -a | grep 'get-cpu-info' | awk '{print $1}')
      - name: Copy file from Docker container
        run: docker cp '$containerID':/cpuinfo .
        
      - name: Check content
        run: cat cpuinfo
